---
- name: create ec2 instance
  ec2:
    region: "{{ aws_region }}"
    zone: "{{ aws_region }}a"
    keypair: "{{ ec2_instance_keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_instance_ami }}"
    vpc_subnet_id: "{{ created_pub_subnet_id }}"
    group_id: "{{ created_secgrp_id }}"
    assign_public_ip: "{{ ec2_instance_pub_ip }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: "{{ ec2_instance_volume_size }}"
        delete_on_termination: true
    count: 1
    wait: yes
    instance_tags:
      Name: "{{ ec2_instance_tag_name }}"
  register: ec2

- name: debug instances 
  debug:
    msg: "{{ ec2.instances[0] }}"

- name: wait for instances to listen on port 22
  wait_for:
    state: started
    host: "{{ ec2.instances[0].public_dns_name }}"
    port: 22
  when: ec2|changed   
 
# we'll get back to that one   
#- name: add new instance to virtual ec2hosts host group
#  add_host: hostname={{ ec2.instances[0].public_ip }} groupname=ec2hosts ansible_ssh_user="{{ec2_config.remote_user}}" ansible_ssh_port=22 ansible_ssh_private_key_file="{{ec2_config.ssh_path}}"
#  with_items: ec2_instances.instances 
