---
- name: create vpc
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    state: "present"
  register: r_created_vpc

- name: set vpc id in variable
  set_fact:
    created_vpc_id: "{{ r_created_vpc.vpc.id }}"

- name: create public subnet
  ec2_vpc_subnet:
    state: "present"
    vpc_id: "{{ created_vpc_id }}"
    cidr: "{{ pub_subnet1_cidr }}"
    az: "{{ aws_region }}a"
    resource_tags:
      Name: "public"
  register: r_created_pub_subnet

- name: set public subnet id in variable
  set_fact:
    created_pub_subnet_id: "{{ r_created_pub_subnet.subnet.id }}"

- name: create internet gateway for vpc
  ec2_vpc_igw:
    vpc_id: "{{ created_vpc_id }}"
    state: "present"
  register: r_created_vpc_igw

- name: set internet gateway id in variable
  set_fact:
    created_vpc_igw_id: "{{ r_created_vpc_igw.gateway_id }}"

- name: route table
  ec2_vpc_route_table:
    vpc_id: "{{ created_vpc_id }}"
    tags:
      Name: "public"
    subnets:
      - "{{ created_pub_subnet_id }}"
    routes:
      - dest: "0.0.0.0/0"
        gateway_id: "{{ created_vpc_igw_id }}"

- name: create main security group
  ec2_group:
    name: "{{ default_secgrp_name }}"
    description: "{{ default_secgrp_desc }}"
    vpc_id: "{{ created_vpc_id }}"
    rules:
      - proto: "tcp"
        from_port: "22"
        to_port: "22"
        cidr_ip: "0.0.0.0/0"
  register: r_created_secgrp

- name: set security group in variable
  set_fact:
    created_secgrp_id: "{{r_created_secgrp.group_id}}"

